alter session set "_ORACLE_SCRIPT"=true;  
SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;
BEGIN
SELECT count(*) into nCount FROM user_tables where table_name = 'USER_ENTITY';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE USER_ENTITY ALREADY EXISTS');
ELSE
EXECUTE IMMEDIATE 'CREATE TABLE USER_ENTITY (
user_id NUMBER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
first_name VARCHAR(12) NOT NULL,
last_name VARCHAR(12) NOT NULL,
email_id VARCHAR(31) unique NOT NULL,
password VARCHAR(20) NOT NULL,
phone_number NUMBER,
tourist_attraction_id NUMBER ,
city_id NUMBER NOT NULL,
date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_of_birth DATE NOT NULL,
CHECK(REGEXP_LIKE(email_id,''^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'')),
CHECK(REGEXP_LIKE(phone_number,''^[0-9]{10}$'')),
)';

END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'COUNTRY';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE COUNTRY ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE COUNTRY (
COUNTRY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY primary key, 
COUNTRY_NAME VARCHAR(20) NOT NULL
)';    

END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'STATES';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE STATES ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE STATES (
STATE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY primary key, 
STATE_NAME VARCHAR(20) NOT NULL,
COUNTRY NUMBER REFERENCES COUNTRY(COUNTRY_id) ON DELETE CASCADE
)';    

END IF;
SELECT count(*) into nCount FROM user_tables where table_name = 'PAYMENT';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE USER_ENTITY ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE PAYMENT(
payment_id INT PRIMARY KEY,
  payment_type_id INT REFERENCES PAYMENT_TYPE(payment_type_id) ON DELETE CASCADE
)';    

END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'PAYMENT_TYPE';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE COUNTRY ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE PAYMENT_TYPE (
payment_type_id INT PRIMARY KEY,
  payment_type_desc VARCHAR(20) NOT NULL
)';    

END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'TOURIST_ATTRACTIONS';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE STATES ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE TOURIST_ATTRACTIONS (
tourist_attraction_id INT PRIMARY KEY,
  tourist_attraction_name varchar(100) NOT NULL,
  city_id INT REFERENCES  CITY(city_id) ON DELETE CASCADE
)';    

END IF;

SELECT count(*) into nCount FROM user_tables where table_name = 'BOOKING_STATUS';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE STATES ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE BOOKING_STATUS (
booking_status_id INT PRIMARY KEY,
  booking_staus VARCHAR(20) NOT NULL
)';    

END IF;



EXCEPTION
        WHEN OTHERS THEN
            dbms_output.put_line(dbms_utility.format_error_backtrace);
            dbms_output.put_line(SQLERRM);
            ROLLBACK;
            RAISE;
COMMIT;
END;

