GRANT SELECT ON ROOM TO SACHIN;
GRANT SELECT ON HOTEL TO SACHIN;
GRANT SELECT ON room_booked_ENTITY TO SACHIN;
GRANT SELECT ON ROOM_TYPE TO SACHIN;
GRANT SELECT ON CITY TO SACHIN;
GRANT SELECT ON tourist_attractions TO SACHIN;





