--dbms_output.put_line('------------- HOTEL SEARCH RELATED ACTIONS -----------'); USER_ACTION_HOTELSEARCH
 

dbms_output.put_line('4. REFER TO ALL THE HOTELS BASED ON USER RATING');-- Dipti

SELECT H.HOTEL_ID, H.HOTEL_NAME,H.STAR_RATING, HC.HOTEL_CHAIN_NAME, H.ADDRESS, H.CHECK_IN_TIME, H.CHECK_OUT_TIME, UR.REVIEW_RATING
FROM HOTEL H LEFT JOIN USER_REVIEWS UR ON H.HOTEL_ID = UR.HOTEL_ID
JOIN HOTEL_CHAIN HC ON H.HOTEL_CHAIN_ID = hc.hotel_chain_id
ORDER BY UR.REVIEW_RATING ;



---- dbms_output.put_line('5. REFER TO ALL THE HOTELS BASED ON HOTEL STAR RATING USING SELECT * FROM ADDRESS_CITY------');-- SHIVANI
SELECT * FROM HOTEL
ORDER BY star_rating;




